title: "My Launchee"
shortcuts:
  - name: "Terminal"
    icon: "/opt/kitty/lib/kitty/logo/kitty-128.png"
    command: "kitty"
    # highlight-next-line
  - name: "Weather"
    icon: "/usr/share/icons/Yaru/48x48@2x/apps/weather-app.png"
    # highlight-next-line
    url: "https://www.accuweather.com/en/es/madrid/308526/weather-forecast/308526?city=madrid"
