// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppVersion() {
  return window['go']['cmd']['Launchee']['GetAppVersion']();
}

export function GetConfig() {
  return window['go']['cmd']['Launchee']['GetConfig']();
}

export function IsBuildForJdvm() {
  return window['go']['cmd']['Launchee']['IsBuildForJdvm']();
}

export function RunCommand(arg1, arg2) {
  return window['go']['cmd']['Launchee']['RunCommand'](arg1, arg2);
}
