// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {frontend} from '../models';

export function GetAppVersion():Promise<string>;

export function GetConfig():Promise<frontend.Config>;

export function IsBuildForJdvm():Promise<boolean>;

export function RunCommand(arg1:Array<string>):Promise<void>;
